server:
  port: 83

spring:
  application:
    name: nacos-payment-consumer #当前服务名称
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址

# 消费者将要去访问的微服务名称(即注册成功进nacos的微服务提供者)
service-url:
  nacos-user-service: http://nacos-payment-provider